export const GET_CHARACTERS = "GET_CHARACTERS";
export const CHARACTERS_LOADING = "CHARACTERS_LOADING";
export const GET_LOCATIONS = "GET_LOCATIONS";
export const LOCATIONS_LOADING = "LOCATIONS_LOADING";
export const GET_EPISODES = "GET_EPISODES";
export const EPISODES_LOADING = "EPISODES_LOADING";